# -*- coding: utf-8 -*-
"""Yet another copy of Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1er5XCSuG2gUPPPWuD7w9sOyhWRmGHNRt
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/spotify_churn_dataset.csv')

df.info()

df.describe()

df.assign()

df.head()

df.tail()

df.dropna(subset='user_id')

df.query('age < 40 and country == "DE"')

df.shape

1

df.hist(figsize=(10,10))
df

sns.pairplot(df)

x=df.drop('gender',axis=1)
y=df['gender']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(
x,y,test_size=0.2,random_state=42
)

x_train

x_test

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Identify categorical columns in x_train
categorical_features = x_train.select_dtypes(include=['object']).columns

# Create a ColumnTransformer to apply OneHotEncoder to categorical features
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough'
)

# Apply the preprocessor to x_train and x_test
x_train_encoded = preprocessor.fit_transform(x_train)
x_test_encoded = preprocessor.transform(x_test)

# Encode the target variable y_train and y_test using LabelEncoder
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

model=LinearRegression()
model.fit(x_train_encoded,y_train_encoded)

from sklearn.metrics import accuracy_score
y_pred=model.predict(x_test_encoded)

y_pred=model.predict(x_test_encoded)
y_pred

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
mse=mean_squared_error(y_test_encoded,y_pred)
mae=mean_absolute_error(y_test_encoded,y_pred)
r_square=r2_score(y_test_encoded,y_pred)
print(f'MSE:{mse}')
print(f'MAE:{mae}')
print(f'R2_Score:{r_square}')